version: "3.8"

services:
  web:
    build: .
    image: php:8.1-apache
    volumes:
      - .:/var/www/html

    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: your_root_password
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
